alias cat="batcat"
alias v="nvim"
alias gd="git diff"
alias gp="git pull"
alias gs="git status"
alias nvn="nvim ~/.config/nvim/"
alias nvk="nvim ~/.config/kitty/kitty.conf"
alias nvq="nvim ~/.config/qtile/config.py"
alias niri-config="nvim ~/.config/niri/config.kdl"
alias altnvim="NVIM_APPNAME=nvim-02 nvim"
alias nvr="nvim +'lua vim.defer_fn(function() vim.cmd(\"RemoteStart\") end, 100)'"
alias sadu="sudo apt-get update && sudo apt-get --auto-remove dist-upgrade"
alias nvm-lts-upgrade="nvm install --lts --reinstall-packages-from=current && npm-check -ug"
alias poff="sudo poweroff"
alias super-claude="claude --dangerously-skip-permissions"
alias ssh="kitten ssh"
