alias cat="batcat"
alias v="nvim"
alias gs="git status"
alias gd="git diff"
alias nvn="nvim ~/.config/nvim/"
alias nvk="nvim ~/.config/kitty/kitty.conf"
alias nvq="nvim ~/.config/qtile/config.py"
alias altnvim="NVIM_APPNAME=nvim-02 nvim"
alias sadu="sudo apt-get update && sudo apt-get --auto-remove dist-upgrade"
